/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paciente;

import BaseDatos.ConexionMySQL;
import Citas.Citas;
import Imagenes.Imagenes;
import Odontograma.Odontograma;
import Pacientes.Pacientes;
import RentarLibro.Rentar;
import Tratamientos.Tratamientos;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.get;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tom
 */
public class Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Paciente
     */
    public Paciente() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLimagen = new javax.swing.JLabel();
        jLIDPaciente = new javax.swing.JLabel();
        JLApellidos = new javax.swing.JLabel();
        JLEdad = new javax.swing.JLabel();
        JSexo = new javax.swing.JLabel();
        JLDomicilio = new javax.swing.JLabel();
        JLCurp = new javax.swing.JLabel();
        jLIdPaciente = new javax.swing.JLabel();
        JLEdad1 = new javax.swing.JLabel();
        JLDomicilio1 = new javax.swing.JLabel();
        JLApellidos1 = new javax.swing.JLabel();
        JSexo1 = new javax.swing.JLabel();
        JLCurp1 = new javax.swing.JLabel();
        JLNombre1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMotivo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        BtnAsignarCita = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLCantidad = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnRegistrarPago = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Regresar = new javax.swing.JLabel();
        jLIDDentista = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnCitaConcluida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID paciente:");

        jLimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RegistrarPaciente/icono.PNG"))); // NOI18N
        jLimagen.setText(" ");

        jLIDPaciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLIDPaciente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLIDPaciente.setText("0");

        JLApellidos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLApellidos.setText("Apellidos");

        JLEdad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLEdad.setText("Edad");

        JSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JSexo.setText("Sexo");

        JLDomicilio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLDomicilio.setText("Domicilio");

        JLCurp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLCurp.setText("CURP");

        jLIdPaciente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLIdPaciente.setText("Nombre(s)");

        JLEdad1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLEdad1.setText("18");

        JLDomicilio1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLDomicilio1.setText("Calle 1, numero 59, colonia Valle");

        JLApellidos1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLApellidos1.setText("Apellido de ejemplo");

        JSexo1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JSexo1.setText("Masculino");

        JLCurp1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLCurp1.setText("IACM960917HMCSSR01");

        JLNombre1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JLNombre1.setText("Nombre de ejemplo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Siguiente Cita");

        jTMotivo.setColumns(20);
        jTMotivo.setRows(5);
        jTMotivo.setText("No hay ninguna cita agendada.\n\nPuedes asignar una en el botón de\nabajo.");
        jScrollPane1.setViewportView(jTMotivo);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Motivo de consulta");

        BtnAsignarCita.setText("Asignar nueva cita");
        BtnAsignarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarCitaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fecha:");

        jLFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLFecha.setText("No Existente");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Cantidad a pagar:");

        jLCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCantidad.setText("$0.00");

        jButton2.setText("Lista de tratamientos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar paciente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnRegistrarPago.setText("Registrar Pago");
        BtnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarPagoActionPerformed(evt);
            }
        });

        jButton6.setText("Agregar nuevo costo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Odontograma");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Regresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });

        jLIDDentista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLIDDentista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLIDDentista.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("ID Dentista:");

        BtnCitaConcluida.setText("Cita concluida");
        BtnCitaConcluida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitaConcluidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(207, 207, 207)
                        .addComponent(Regresar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BtnAsignarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BtnCitaConcluida, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRegistrarPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLimagen)
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLIdPaciente)
                                .addComponent(JLApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLDomicilio1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLCurp1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(jLIDDentista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLIDDentista)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLIDPaciente)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLimagen)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLIdPaciente)
                                .addGap(11, 11, 11)
                                .addComponent(JLApellidos)
                                .addGap(11, 11, 11)
                                .addComponent(JLEdad)
                                .addGap(11, 11, 11)
                                .addComponent(JSexo)
                                .addGap(11, 11, 11)
                                .addComponent(JLDomicilio)
                                .addGap(11, 11, 11)
                                .addComponent(JLCurp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLNombre1)
                                .addGap(11, 11, 11)
                                .addComponent(JLApellidos1)
                                .addGap(11, 11, 11)
                                .addComponent(JLEdad1)
                                .addGap(11, 11, 11)
                                .addComponent(JSexo1)
                                .addGap(11, 11, 11)
                                .addComponent(JLDomicilio1)
                                .addGap(11, 11, 11)
                                .addComponent(JLCurp1)))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(11, 11, 11)
                        .addComponent(BtnRegistrarPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAsignarCita)
                    .addComponent(BtnCitaConcluida))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFecha)
                        .addGap(8, 8, 8)
                        .addComponent(jLCantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Regresar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int codigo=JOptionPane.showConfirmDialog(null, "¿Seguro que quieres Eliminarlo?", "Mensaje de confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (codigo==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"Paciente eliminado","Mensaje",JOptionPane.INFORMATION_MESSAGE);  
            Pacientes eliminar=new Pacientes();
            eliminar.setLocationRelativeTo(null);
            eliminar.setVisible(true);
            this.setVisible(false);
        }
        else if(codigo==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,"Paciente no eliminado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();
        Odontograma verOdont = new Odontograma();
        try {
            Statement s1 = cn.createStatement();
            ResultSet rs1 = s1.executeQuery("SELECT * FROM odontograma WHERE idOdontograma = '" + jLIDPaciente.getText() + "'");
            while(rs1.next()){ 
                verOdont.JLDiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(2).toString()+".png")));
                verOdont.JLDiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(3).toString()+".png")));
                verOdont.JLDiente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(4).toString()+".png")));
                verOdont.JLDiente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(5).toString()+".png")));
                verOdont.JLDiente5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(6).toString()+".png")));
                verOdont.JLDiente6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(7).toString()+".png")));
                verOdont.JLDiente7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(8).toString()+".png")));
                verOdont.JLDiente8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(9).toString()+".png")));
                verOdont.JLDiente9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(10).toString()+".png")));
                verOdont.JLDiente10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(11).toString()+".png")));       
                verOdont.JLDiente11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(12).toString()+".png")));
                verOdont.JLDiente12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(13).toString()+".png")));
                verOdont.JLDiente13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(14).toString()+".png")));
                verOdont.JLDiente14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(15).toString()+".png")));
                verOdont.JLDiente15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(16).toString()+".png")));
                verOdont.JLDiente16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(17).toString()+".png")));
                verOdont.JLDiente17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(18).toString()+".png")));
                verOdont.JLDiente18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(19).toString()+".png")));
                verOdont.JLDiente19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(20).toString()+".png")));
                verOdont.JLDiente20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(21).toString()+".png")));       
                verOdont.JLDiente21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(22).toString()+".png")));
                verOdont.JLDiente22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(23).toString()+".png")));
                verOdont.JLDiente23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(24).toString()+".png")));
                verOdont.JLDiente24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(25).toString()+".png")));
                verOdont.JLDiente25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(26).toString()+".png")));
                verOdont.JLDiente26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(27).toString()+".png")));
                verOdont.JLDiente27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(28).toString()+".png")));
                verOdont.JLDiente28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(29).toString()+".png")));
                verOdont.JLDiente29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(30).toString()+".png")));
                verOdont.JLDiente30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(31).toString()+".png")));       
                verOdont.JLDiente31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(32).toString()+".png")));
                verOdont.JLDiente32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(33).toString()+".png")));
                int i;
                for (i=0;i<32;i++){
                    verOdont.problema[i]=Integer.parseInt(rs1.getObject(i+2).toString());
                }
            }            
            rs1.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }
        
        
        verOdont.jLIDDentista.setText(jLIDDentista.getText());    
        verOdont.jLIDPaciente.setText(jLIDPaciente.getText());
        verOdont.setLocationRelativeTo(null);
        verOdont.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        // TODO add your handling code here:
        Pacientes cancelar=new Pacientes();
        cancelar.setLocationRelativeTo(null);
        cancelar.jLIDDentista.setText(jLIDDentista.getText());
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();
        try {
            Statement s1 = cn.createStatement();
            ResultSet rs1 = s1.executeQuery("SELECT idPaciente,nombres FROM paciente WHERE dentistaAsignado = '" + jLIDDentista.getText() + "' AND mostrar = 1");     
            ResultSetMetaData rsmd=rs1.getMetaData();        
            int numeroColumnas=rsmd.getColumnCount();
            DefaultTableModel modelo=new DefaultTableModel();
            cancelar.TablaPacientes.setModel(modelo);
            for(int x=1;x<=numeroColumnas;x++){
                modelo.addColumn(rsmd.getColumnName(x));
            }        
            while(rs1.next()){
                Object [] fila=new Object[numeroColumnas];
                for(int y=0;y<numeroColumnas;y++){
                    fila [y] =(String) rs1.getObject(y+1).toString();
                }
            modelo.addRow(fila);
            }
            rs1.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }
        cancelar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        float cantidadPagada=0;
        float cantidadDebida=0;      
        String motivo;
        float cantidad;
        cantidad=Float.parseFloat(JOptionPane.showInputDialog(null,"Introduce la cantidad que paragrá"));
        motivo=JOptionPane.showInputDialog(null,"Motivo del costo");
        cantidadDebida=cantidad;
        DecimalFormat df = new DecimalFormat("0.00"); 
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();  
        try {
            Statement s = cn.createStatement();
            ResultSet rs = s.executeQuery("SELECT cantidadPagada FROM paciente WHERE idPaciente = '"+jLIDPaciente.getText()+"'"); 
            while(rs.next()){
                cantidadPagada=Float.parseFloat((String) rs.getObject(1).toString());
            }
            rs.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }           
        try {
            Statement s = cn.createStatement();
            ResultSet rs = s.executeQuery("SELECT cantidad FROM costos WHERE idPaciente = '"+jLIDPaciente.getText()+"'"); 
            while(rs.next()){
                cantidadDebida+=Float.parseFloat((String) rs.getObject(1).toString());
            }
            rs.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }   
        try {
            String aSQL="insert into costos (cantidad,descripcion,idPaciente) Values ('"+df.format(cantidad)+"','"+motivo+"',"+jLIDPaciente.getText()+");";
            PreparedStatement pst=cn.prepareStatement(aSQL);
            pst.executeUpdate();
            jLCantidad.setText("$"+df.format(cantidadDebida-cantidadPagada));            
        }        
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();        
        Tratamientos verTrat=new Tratamientos();
        try {
            Statement s1 = cn.createStatement();
            ResultSet rs1 = s1.executeQuery("SELECT idTratamiento,duracion,tratamientoActual,fechaInicio FROM tratamientos WHERE idPaciente = '" + jLIDPaciente.getText() + "' AND finalizado = 0");     
            ResultSetMetaData rsmd=rs1.getMetaData();        
            int numeroColumnas=rsmd.getColumnCount();
            DefaultTableModel modelo=new DefaultTableModel();
            verTrat.jTTabla.setModel(modelo);
            modelo.addColumn("Id Traramiento");
            modelo.addColumn("Duración (sesiones)");
            modelo.addColumn("Tratamiento actual");
            modelo.addColumn("Fecha de inicio");
            /**for(int x=1;x<=numeroColumnas;x++){
                modelo.addColumn(rsmd.getColumnName(x));
            }     */
            while(rs1.next()){
                Object [] fila=new Object[numeroColumnas];
                for(int y=0;y<numeroColumnas;y++){
                if (((String) rs1.getObject(y+1).toString()).equals("false")){
                    fila [y]="No";
                }
                else if (((String) rs1.getObject(y+1).toString()).equals("true")){
                    fila [y]="Sí";
                }
                else{
                    fila [y] =(String) rs1.getObject(y+1).toString();                    
                }
            }
            modelo.addRow(fila);
            }
            rs1.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }        
        verTrat.jLIDDentista.setText(jLIDDentista.getText());        
        verTrat.jLIDPaciente.setText(jLIDPaciente.getText());
        verTrat.setLocationRelativeTo(null);
        verTrat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnAsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarCitaActionPerformed
        // TODO add your handling code here:
       Citas abrir=new Citas();
       abrir.setLocationRelativeTo(null);
       abrir.jLIDDentista.setText(jLIDDentista.getText());
       abrir.jLIDPaciente.setText(jLIDPaciente.getText());
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAsignarCitaActionPerformed

    private void BtnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarPagoActionPerformed
        // TODO add your handling code here:
        float cantidadPagada=0;
        float cantidadDebida=0;        
        DecimalFormat df = new DecimalFormat("0.00"); 
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();  
        
        try {
                    Statement s = cn.createStatement();
                    ResultSet rs = s.executeQuery("SELECT cantidadPagada FROM paciente WHERE idPaciente = '"+jLIDPaciente.getText()+"'"); 
                    while(rs.next()){
                        cantidadPagada=Float.parseFloat((String) rs.getObject(1).toString());
                    }
                    rs.close();
                }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }   
        try {
                    Statement s = cn.createStatement();
                    ResultSet rs = s.executeQuery("SELECT cantidad FROM costos WHERE idPaciente = '"+jLIDPaciente.getText()+"'"); 
                    while(rs.next()){
                        cantidadDebida+=Float.parseFloat((String) rs.getObject(1).toString());
                    }
                    rs.close();
                }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }   
        
        
        cantidadPagada+=Float.parseFloat(JOptionPane.showInputDialog(null,"Introduce la cantidad que paragrá"));
        JOptionPane.showMessageDialog(null, "Ingresos totales recibidos por este paciente: "+cantidadPagada);
        
        try {
            String aSQL="UPDATE paciente SET cantidadPagada='"+df.format(cantidadPagada)+"' WHERE idPaciente='"+jLIDPaciente.getText()+"'";
            String aSQLCosto = "UPDATE costos SET cantidad='"+df.format(cantidadDebida-cantidadPagada)+"' WHERE idPaciente='"+jLIDPaciente.getText()+"'";
            PreparedStatement pst=cn.prepareStatement(aSQL);
            PreparedStatement pst1 = cn.prepareStatement(aSQLCosto);
            pst.executeUpdate();
            pst1.executeUpdate();
            jLCantidad.setText("$"+df.format(cantidadDebida-cantidadPagada));            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }
    }//GEN-LAST:event_BtnRegistrarPagoActionPerformed

    private void BtnCitaConcluidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitaConcluidaActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();  
        try {
            //String aSQL="UPDATE citas SET actual='0' WHERE actual='1' and idPaciente='"+jLIDPaciente.getText()+"'";
            String aSQL="DELETE FROM citas WHERE idPaciente='"+jLIDPaciente.getText()+"'";
            PreparedStatement pst=cn.prepareStatement(aSQL);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "La cita ha finalizado");
            jTMotivo.setText("No hay ninguna cita agendada.\n\nPuedes asignar una en el botón de\nabajo.");
            jLFecha.setText("No Existente");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Problema al conectar");
        }
    }//GEN-LAST:event_BtnCitaConcluidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAsignarCita;
    private javax.swing.JButton BtnCitaConcluida;
    private javax.swing.JButton BtnRegistrarPago;
    private javax.swing.JLabel JLApellidos;
    public javax.swing.JLabel JLApellidos1;
    private javax.swing.JLabel JLCurp;
    public javax.swing.JLabel JLCurp1;
    private javax.swing.JLabel JLDomicilio;
    public javax.swing.JLabel JLDomicilio1;
    private javax.swing.JLabel JLEdad;
    public javax.swing.JLabel JLEdad1;
    public javax.swing.JLabel JLNombre1;
    private javax.swing.JLabel JSexo;
    public javax.swing.JLabel JSexo1;
    private javax.swing.JLabel Regresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public javax.swing.JLabel jLCantidad;
    public javax.swing.JLabel jLFecha;
    public javax.swing.JLabel jLIDDentista;
    public javax.swing.JLabel jLIDPaciente;
    private javax.swing.JLabel jLIdPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLimagen;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTMotivo;
    // End of variables declaration//GEN-END:variables
}
