/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Odontograma;

import BaseDatos.ConexionMySQL;
import Citas.Citas;
import Paciente.Paciente;
import Tratamientos.RegistrarTraramiento;
import Tratamientos.Tratamientos;
import java.awt.Cursor;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author telmex
 */
public class Odontograma extends javax.swing.JFrame {

    /**
     * Creates new form Odontograma
     */
    public Odontograma() {
        initComponents();
        JLDiente1.setCursor(new Cursor(HAND_CURSOR));
        JLDiente2.setCursor(new Cursor(HAND_CURSOR));
        JLDiente3.setCursor(new Cursor(HAND_CURSOR));
        JLDiente4.setCursor(new Cursor(HAND_CURSOR));
        JLDiente5.setCursor(new Cursor(HAND_CURSOR));
        JLDiente6.setCursor(new Cursor(HAND_CURSOR));
        JLDiente7.setCursor(new Cursor(HAND_CURSOR));
        JLDiente8.setCursor(new Cursor(HAND_CURSOR));
        JLDiente9.setCursor(new Cursor(HAND_CURSOR));
        JLDiente10.setCursor(new Cursor(HAND_CURSOR));
        JLDiente11.setCursor(new Cursor(HAND_CURSOR));
        JLDiente12.setCursor(new Cursor(HAND_CURSOR));
        JLDiente13.setCursor(new Cursor(HAND_CURSOR));
        JLDiente14.setCursor(new Cursor(HAND_CURSOR));
        JLDiente15.setCursor(new Cursor(HAND_CURSOR));
        JLDiente16.setCursor(new Cursor(HAND_CURSOR));
        JLDiente17.setCursor(new Cursor(HAND_CURSOR));
        JLDiente18.setCursor(new Cursor(HAND_CURSOR));
        JLDiente19.setCursor(new Cursor(HAND_CURSOR));        
        JLDiente20.setCursor(new Cursor(HAND_CURSOR));
        JLDiente21.setCursor(new Cursor(HAND_CURSOR));
        JLDiente22.setCursor(new Cursor(HAND_CURSOR));
        JLDiente23.setCursor(new Cursor(HAND_CURSOR));
        JLDiente24.setCursor(new Cursor(HAND_CURSOR));
        JLDiente25.setCursor(new Cursor(HAND_CURSOR));
        JLDiente26.setCursor(new Cursor(HAND_CURSOR));
        JLDiente27.setCursor(new Cursor(HAND_CURSOR));
        JLDiente28.setCursor(new Cursor(HAND_CURSOR));
        JLDiente29.setCursor(new Cursor(HAND_CURSOR));
        JLDiente30.setCursor(new Cursor(HAND_CURSOR));
        JLDiente31.setCursor(new Cursor(HAND_CURSOR));
        JLDiente32.setCursor(new Cursor(HAND_CURSOR));
        problemaEsp[0]="Ninguno";
        problemaEsp[1]="Caries";
        problemaEsp[2]="Pulpitis";
        problemaEsp[3]="Paradontitis apical";        
        problemaEsp[4]="Otro";
        jTDescipcion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTDescipcion = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLIDPaciente = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLIDDentista = new javax.swing.JLabel();
        JLDiente1 = new javax.swing.JLabel();
        JLDiente2 = new javax.swing.JLabel();
        JLDiente3 = new javax.swing.JLabel();
        JLDiente4 = new javax.swing.JLabel();
        JLDiente5 = new javax.swing.JLabel();
        JLDiente6 = new javax.swing.JLabel();
        JLDiente7 = new javax.swing.JLabel();
        JLDiente8 = new javax.swing.JLabel();
        JLDiente9 = new javax.swing.JLabel();
        JLDiente10 = new javax.swing.JLabel();
        JLDiente11 = new javax.swing.JLabel();
        JLDiente12 = new javax.swing.JLabel();
        JLDiente13 = new javax.swing.JLabel();
        JLDiente14 = new javax.swing.JLabel();
        JLDiente15 = new javax.swing.JLabel();
        JLDiente16 = new javax.swing.JLabel();
        JLDiente17 = new javax.swing.JLabel();
        JLDiente18 = new javax.swing.JLabel();
        JLDiente19 = new javax.swing.JLabel();
        JLDiente20 = new javax.swing.JLabel();
        JLDiente21 = new javax.swing.JLabel();
        JLDiente22 = new javax.swing.JLabel();
        JLDiente23 = new javax.swing.JLabel();
        JLDiente24 = new javax.swing.JLabel();
        JLDiente25 = new javax.swing.JLabel();
        JLDiente26 = new javax.swing.JLabel();
        JLDiente27 = new javax.swing.JLabel();
        JLDiente28 = new javax.swing.JLabel();
        JLDiente29 = new javax.swing.JLabel();
        JLDiente30 = new javax.swing.JLabel();
        JLDiente31 = new javax.swing.JLabel();
        JLDiente32 = new javax.swing.JLabel();
        Odontograma = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLDienteSel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(750, 520));
        setMinimumSize(new java.awt.Dimension(750, 520));
        setResizable(false);

        jTDescipcion.setColumns(20);
        jTDescipcion.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTDescipcion.setRows(5);
        jTDescipcion.setText("Descripción \ndel diente");
        jScrollPane1.setViewportView(jTDescipcion);

        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel14.setText("                     Descripción");

        jLIDPaciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLIDPaciente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLIDPaciente.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("ID paciente:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("ID Dentista:");

        jLIDDentista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLIDDentista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLIDDentista.setText("0");

        JLDiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente1.setText("01");
        JLDiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente1MouseClicked(evt);
            }
        });

        JLDiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente2.setText("02");
        JLDiente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente2MouseClicked(evt);
            }
        });

        JLDiente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente3.setText("03");
        JLDiente3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente3MouseClicked(evt);
            }
        });

        JLDiente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente4.setText("04");
        JLDiente4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente4MouseClicked(evt);
            }
        });

        JLDiente5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente5.setText("05");
        JLDiente5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente5MouseClicked(evt);
            }
        });

        JLDiente6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente6.setText("06");
        JLDiente6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente6MouseClicked(evt);
            }
        });

        JLDiente7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente7.setText("07");
        JLDiente7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente7MouseClicked(evt);
            }
        });

        JLDiente8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente8.setText("08");
        JLDiente8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente8MouseClicked(evt);
            }
        });

        JLDiente9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente9.setText("09");
        JLDiente9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente9MouseClicked(evt);
            }
        });

        JLDiente10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente10.setText("10");
        JLDiente10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente10MouseClicked(evt);
            }
        });

        JLDiente11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente11.setText("11");
        JLDiente11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente11MouseClicked(evt);
            }
        });

        JLDiente12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente12.setText("12");
        JLDiente12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente12MouseClicked(evt);
            }
        });

        JLDiente13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente13.setText("13");
        JLDiente13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente13MouseClicked(evt);
            }
        });

        JLDiente14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente14.setText("14");
        JLDiente14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente14MouseClicked(evt);
            }
        });

        JLDiente15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente15.setText("15");
        JLDiente15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente15MouseClicked(evt);
            }
        });

        JLDiente16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente16.setText("16");
        JLDiente16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente16MouseClicked(evt);
            }
        });

        JLDiente17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente17.setText("17");
        JLDiente17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente17MouseClicked(evt);
            }
        });

        JLDiente18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente18.setText("18");
        JLDiente18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente18MouseClicked(evt);
            }
        });

        JLDiente19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente19.setText("19");
        JLDiente19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente19MouseClicked(evt);
            }
        });

        JLDiente20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente20.setText("20");
        JLDiente20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente20MouseClicked(evt);
            }
        });

        JLDiente21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente21.setText("21");
        JLDiente21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente21MouseClicked(evt);
            }
        });

        JLDiente22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente22.setText("22");
        JLDiente22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente22MouseClicked(evt);
            }
        });

        JLDiente23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente23.setText("23");
        JLDiente23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente23MouseClicked(evt);
            }
        });

        JLDiente24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente24.setText("24");
        JLDiente24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente24MouseClicked(evt);
            }
        });

        JLDiente25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente25.setText("25");
        JLDiente25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente25MouseClicked(evt);
            }
        });

        JLDiente26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente26.setText("26");
        JLDiente26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente26MouseClicked(evt);
            }
        });

        JLDiente27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente27.setText("27");
        JLDiente27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente27MouseClicked(evt);
            }
        });

        JLDiente28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente28.setText("28");
        JLDiente28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente28MouseClicked(evt);
            }
        });

        JLDiente29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente29.setText("29");
        JLDiente29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente29MouseClicked(evt);
            }
        });

        JLDiente30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente30.setText("30");
        JLDiente30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente30MouseClicked(evt);
            }
        });

        JLDiente31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente31.setText("31");
        JLDiente31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente31MouseClicked(evt);
            }
        });

        JLDiente32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/Odont.png"))); // NOI18N
        JLDiente32.setText("32");
        JLDiente32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLDiente32MouseClicked(evt);
            }
        });

        Odontograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/OdontogramaFinal.png"))); // NOI18N

        jButton11.setText("Modificar diente");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton1.setText("Agendar cita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear tratamiento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dientes");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Odontograma");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Diente seleccionado:");

        jLDienteSel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDienteSel.setText("Ninguno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addComponent(jLIDDentista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDiente1)
                            .addComponent(JLDiente9)
                            .addComponent(JLDiente17)
                            .addComponent(JLDiente25))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDiente2)
                            .addComponent(JLDiente10)
                            .addComponent(JLDiente18)
                            .addComponent(JLDiente26))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDiente3)
                            .addComponent(JLDiente11)
                            .addComponent(JLDiente19)
                            .addComponent(JLDiente27))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDiente4)
                            .addComponent(JLDiente12)
                            .addComponent(JLDiente20)
                            .addComponent(JLDiente28))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLDiente5)
                                .addGap(14, 14, 14)
                                .addComponent(JLDiente6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLDiente13)
                                .addGap(14, 14, 14)
                                .addComponent(JLDiente14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLDiente21)
                                .addGap(14, 14, 14)
                                .addComponent(JLDiente22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLDiente29)
                                .addGap(14, 14, 14)
                                .addComponent(JLDiente30)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDiente7)
                            .addComponent(JLDiente15)
                            .addComponent(JLDiente23)
                            .addComponent(JLDiente31))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDiente8)
                            .addComponent(JLDiente16)
                            .addComponent(JLDiente24)
                            .addComponent(JLDiente32)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLDienteSel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Odontograma)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIDDentista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLDienteSel))
                        .addGap(34, 34, 34)
                        .addComponent(Odontograma)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLDiente5)
                                        .addComponent(JLDiente6))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLDiente13)
                                        .addComponent(JLDiente14))
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLDiente21)
                                        .addComponent(JLDiente22))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLDiente29)
                                        .addComponent(JLDiente30)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JLDiente8)
                                            .addGap(10, 10, 10)
                                            .addComponent(JLDiente16))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JLDiente7)
                                            .addGap(10, 10, 10)
                                            .addComponent(JLDiente15)))
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JLDiente23)
                                            .addGap(10, 10, 10)
                                            .addComponent(JLDiente31))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(JLDiente24)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(JLDiente32)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLDiente1)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente9)
                                    .addGap(60, 60, 60)
                                    .addComponent(JLDiente17)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente25))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLDiente2)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente10)
                                    .addGap(60, 60, 60)
                                    .addComponent(JLDiente18)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente26))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLDiente3)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente11)
                                    .addGap(60, 60, 60)
                                    .addComponent(JLDiente19)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente27))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JLDiente4)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente12)
                                    .addGap(60, 60, 60)
                                    .addComponent(JLDiente20)
                                    .addGap(10, 10, 10)
                                    .addComponent(JLDiente28))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton10)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int numeroDiente=0;
    public int[] problema=new int[32];
    String[] problemaEsp=new String[5];
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
        boolean i=false;
        try {
            Statement s1 = cn.createStatement();
            ResultSet rs1 = s1.executeQuery("SELECT nombres,apellidos,edad,sexo,domicilio,curp,dentistaAsignado FROM paciente WHERE mostrar = 1 AND idPaciente = '"+jLIDPaciente.getText()+"'"); 
            while(rs1.next()){
                String sFichero = "src\\ImagenesPaciente\\"+jLIDPaciente.getText()+".jpg";
                File fichero = new File(sFichero);
                ImageIcon icon;
                if (fichero.exists())
                {
                  icon=new ImageIcon("src\\ImagenesPaciente\\"+jLIDPaciente.getText()+".jpg");  
                }
                else
                {
                   icon=new ImageIcon("src\\ImagenesPaciente\\SinImagen.png");  
                }
                Image img= icon.getImage();
                Image newimg = img.getScaledInstance(150, 175, java.awt.Image.SCALE_SMOOTH);
                ImageIcon newIcon = new ImageIcon(newimg);
                Paciente verPaciente=new Paciente();
                try {
                    Statement s2 = cn.createStatement();
                    ResultSet rs2 = s2.executeQuery("SELECT fecha,Descripción FROM citas WHERE idPaciente = '"+jLIDPaciente.getText()+"' AND actual='1'"); 
                    while(rs2.next()){
                        verPaciente.jLFecha.setText((String) rs2.getObject(1).toString());
                        verPaciente.jTMotivo.setText((String) rs2.getObject(2).toString());
                    }
                    rs2.close();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Problema al conectar");
                } 
                // COSTO 
                float cantidadPagada=0;
                float cantidadDebida=0;                
                DecimalFormat df = new DecimalFormat("0.00"); 
                try {
                    Statement s = cn.createStatement();
                    ResultSet rs = s.executeQuery("SELECT cantidadPagada FROM paciente WHERE idPaciente = '"+jLIDPaciente.getText()+"'"); 
                    while(rs.next()){
                        cantidadPagada=Float.parseFloat((String) rs.getObject(1).toString());
                    }
                    rs.close();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Problema al conectar");
                }           
                try {
                    Statement s = cn.createStatement();
                    ResultSet rs = s.executeQuery("SELECT cantidad FROM costos WHERE idPaciente = '"+jLIDPaciente.getText()+"'"); 
                    while(rs.next()){
                        cantidadDebida+=Float.parseFloat((String) rs.getObject(1).toString());
                    }
                    rs.close();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Problema al conectar");
                }    
                verPaciente.jLCantidad.setText("$"+df.format(cantidadDebida-cantidadPagada));
                //Aqui acaba costo
                verPaciente.JLNombre1.setText((String) rs1.getObject(1).toString());
                verPaciente.JLApellidos1.setText((String) rs1.getObject(2).toString());
                verPaciente.JLEdad1.setText((String) rs1.getObject(3).toString());
                verPaciente.JSexo1.setText((String) rs1.getObject(4));
                verPaciente.JLDomicilio1.setText((String) rs1.getObject(5).toString());
                verPaciente.JLCurp1.setText((String) rs1.getObject(6).toString());
                verPaciente.jLimagen.setIcon(newIcon);
                verPaciente.jLimagen.setSize(150,175);   
                verPaciente.setLocationRelativeTo(null);
                verPaciente.jLIDDentista.setText((String) rs1.getObject(7).toString());
                verPaciente.jLIDPaciente.setText(jLIDPaciente.getText());
                verPaciente.setTitle("Información de: "+rs1.getObject(1).toString());
                verPaciente.setVisible(true);
                this.setVisible(false);
                i=true;
            }
            if(i==false){
                JOptionPane.showMessageDialog(null,"El paciente no existe o le corresponde a otro doctor");
            }
            rs1.close();
        }
            catch(SQLException e){
		JOptionPane.showMessageDialog(null,"Problema al conectar");
            }    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Citas abrir=new Citas();
       abrir.setLocationRelativeTo(null);
       abrir.jLIDDentista.setText(jLIDDentista.getText());
       abrir.jLIDPaciente.setText(jLIDPaciente.getText());
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RegistrarTraramiento RegT = new RegistrarTraramiento();
        RegT.jLIDDentista.setText(jLIDDentista.getText());
        RegT.jLIDPaciente.setText(jLIDPaciente.getText());
        RegT.setLocationRelativeTo(null);
        RegT.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int seleccion=0;
        String[] tipos = { "Caries", "Pulpitis", "Paradontitis apical", "Otro","Ninguno"};
        if(!jLDienteSel.getText().equals("Ninguno")){
            String opcion=(String) JOptionPane.showInputDialog(null, "¿Qué problema tiene el diente "+jLDienteSel.getText()+"?\n","Selecciona una opción",JOptionPane.QUESTION_MESSAGE,null,tipos,tipos[0]);
            if (opcion!=null){
                if (opcion.equals("Caries")){
                    seleccion=1;
                }
                else if (opcion.equals("Pulpitis")){
                    seleccion=2;
                }
                else if (opcion.equals("Paradontitis apical")){
                    seleccion=3;
                }
                else if (opcion.equals("Otro")){
                    seleccion=4;
                }
                else if (opcion.equals("Ninguno")){
                    seleccion=0;
                }
                
                ConexionMySQL mysql = new ConexionMySQL();
                Connection cn= mysql.Conectar();  
                try {
                    String aSQL="UPDATE odontograma SET diente"+jLDienteSel.getText()+"='"+seleccion+"' WHERE  idOdontograma='"+jLIDPaciente.getText()+"'";
                    PreparedStatement pst=cn.prepareStatement(aSQL);
                    pst.executeUpdate();
                    try {
                        Statement s1 = cn.createStatement();
                        ResultSet rs1 = s1.executeQuery("SELECT * FROM odontograma WHERE idOdontograma = '" + jLIDPaciente.getText() + "'");
                        while(rs1.next()){ 
                            JLDiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(2).toString()+".png")));
                            JLDiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(3).toString()+".png")));
                            JLDiente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(4).toString()+".png")));
                            JLDiente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(5).toString()+".png")));
                            JLDiente5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(6).toString()+".png")));
                            JLDiente6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(7).toString()+".png")));
                            JLDiente7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(8).toString()+".png")));
                            JLDiente8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(9).toString()+".png")));
                            JLDiente9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(10).toString()+".png")));
                            JLDiente10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(11).toString()+".png")));       
                            JLDiente11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(12).toString()+".png")));
                            JLDiente12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(13).toString()+".png")));
                            JLDiente13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(14).toString()+".png")));
                            JLDiente14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(15).toString()+".png")));
                            JLDiente15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(16).toString()+".png")));
                            JLDiente16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(17).toString()+".png")));
                            JLDiente17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(18).toString()+".png")));
                            JLDiente18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(19).toString()+".png")));
                            JLDiente19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(20).toString()+".png")));
                            JLDiente20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(21).toString()+".png")));       
                            JLDiente21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(22).toString()+".png")));
                            JLDiente22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(23).toString()+".png")));
                            JLDiente23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(24).toString()+".png")));
                            JLDiente24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(25).toString()+".png")));
                            JLDiente25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(26).toString()+".png")));
                            JLDiente26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(27).toString()+".png")));
                            JLDiente27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(28).toString()+".png")));
                            JLDiente28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(29).toString()+".png")));
                            JLDiente29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(30).toString()+".png")));
                            JLDiente30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(31).toString()+".png")));       
                            JLDiente31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(32).toString()+".png")));
                            JLDiente32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Odontograma/"+rs1.getObject(33).toString()+".png")));
                            int i;
                            for (i=0;i<32;i++){
                                problema[i]=Integer.parseInt(rs1.getObject(i+2).toString());
                            }                            
                            JOptionPane.showMessageDialog(null, "Se ha actualizado el diente");
                            jLDienteSel.setText("Ninguno");
                        }            
                        rs1.close();
                    }
                    catch(SQLException e){
                        JOptionPane.showMessageDialog(null,"Problema al conectar");
                    }
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Problema al conectar");
                }
            }
            else{
             JOptionPane.showMessageDialog(null, "No seleccionaste opcion");
            }
        }        
        else{            
            JOptionPane.showMessageDialog(null, "No hay ningun diente seleccionado");
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void JLDiente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente1MouseClicked
        // Diente numero 1
        numeroDiente=1;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente1MouseClicked

    private void JLDiente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente2MouseClicked
        // Diente numero 2
        numeroDiente=2;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente2MouseClicked

    private void JLDiente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente3MouseClicked
    // Diente numero 3
        numeroDiente=3;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente3MouseClicked

    private void JLDiente4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente4MouseClicked
    // Diente numero 4
        numeroDiente=4;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente4MouseClicked

    private void JLDiente5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente5MouseClicked
    // Diente numero 5
        numeroDiente=5;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente5MouseClicked

    private void JLDiente6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente6MouseClicked
    // Diente numero 6
        numeroDiente=6;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente6MouseClicked

    private void JLDiente7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente7MouseClicked
    // Diente numero 7
        numeroDiente=7;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente7MouseClicked

    private void JLDiente8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente8MouseClicked
    // Diente numero 8
        numeroDiente=8;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente8MouseClicked

    private void JLDiente9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente9MouseClicked
    // Diente numero 9
        numeroDiente=9;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente9MouseClicked

    private void JLDiente10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente10MouseClicked
    // Diente numero 10
        numeroDiente=10;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente10MouseClicked

    private void JLDiente11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente11MouseClicked
    // Diente numero 11
        numeroDiente=11;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente11MouseClicked

    private void JLDiente12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente12MouseClicked
    // Diente numero 12
        numeroDiente=12;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente12MouseClicked

    private void JLDiente13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente13MouseClicked
    // Diente numero 13
        numeroDiente=13;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente13MouseClicked

    private void JLDiente14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente14MouseClicked
    // Diente numero 14
        numeroDiente=14;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente14MouseClicked

    private void JLDiente15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente15MouseClicked
    // Diente numero 15
        numeroDiente=15;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente15MouseClicked

    private void JLDiente16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente16MouseClicked
    // Diente numero 16
        numeroDiente=16;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente16MouseClicked

    private void JLDiente17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente17MouseClicked
    // Diente numero 17
        numeroDiente=17;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente17MouseClicked

    private void JLDiente18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente18MouseClicked
    // Diente numero 18
        numeroDiente=18;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente18MouseClicked

    private void JLDiente19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente19MouseClicked
    // Diente numero 19
        numeroDiente=19;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente19MouseClicked

    private void JLDiente20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente20MouseClicked
        // Diente numero 20
        numeroDiente=20;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente20MouseClicked

    private void JLDiente21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente21MouseClicked
        // Diente numero 21
        numeroDiente=21;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente21MouseClicked

    private void JLDiente22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente22MouseClicked
        // Diente numero 22
        numeroDiente=22;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente22MouseClicked

    private void JLDiente23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente23MouseClicked
        // Diente numero 23
        numeroDiente=23;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente23MouseClicked

    private void JLDiente24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente24MouseClicked
        // Diente numero 24
        numeroDiente=24;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente24MouseClicked

    private void JLDiente25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente25MouseClicked
        // Diente numero 25
        numeroDiente=25;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente25MouseClicked

    private void JLDiente26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente26MouseClicked
        // Diente numero 26
        numeroDiente=26;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente26MouseClicked

    private void JLDiente27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente27MouseClicked
        // Diente numero 27
        numeroDiente=27;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente27MouseClicked

    private void JLDiente28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente28MouseClicked
        // Diente numero 28
        numeroDiente=28;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente28MouseClicked

    private void JLDiente29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente29MouseClicked
        // Diente numero 29
        numeroDiente=29;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente29MouseClicked

    private void JLDiente30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente30MouseClicked
        // Diente numero 30
        numeroDiente=30;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente30MouseClicked

    private void JLDiente31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente31MouseClicked
        // Diente numero 31
        numeroDiente=31;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente31MouseClicked

    private void JLDiente32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLDiente32MouseClicked
        // Diente numero 32
        numeroDiente=32;
        if(problema[numeroDiente-1]>0)
            jTDescipcion.setText("El problema de este diente es: \n"+problemaEsp[problema[numeroDiente-1]]);
        else
            jTDescipcion.setText("No tiene ningun \nproblema este diente. ");
        jLDienteSel.setText(""+numeroDiente);
    }//GEN-LAST:event_JLDiente32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odontograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLDiente1;
    public javax.swing.JLabel JLDiente10;
    public javax.swing.JLabel JLDiente11;
    public javax.swing.JLabel JLDiente12;
    public javax.swing.JLabel JLDiente13;
    public javax.swing.JLabel JLDiente14;
    public javax.swing.JLabel JLDiente15;
    public javax.swing.JLabel JLDiente16;
    public javax.swing.JLabel JLDiente17;
    public javax.swing.JLabel JLDiente18;
    public javax.swing.JLabel JLDiente19;
    public javax.swing.JLabel JLDiente2;
    public javax.swing.JLabel JLDiente20;
    public javax.swing.JLabel JLDiente21;
    public javax.swing.JLabel JLDiente22;
    public javax.swing.JLabel JLDiente23;
    public javax.swing.JLabel JLDiente24;
    public javax.swing.JLabel JLDiente25;
    public javax.swing.JLabel JLDiente26;
    public javax.swing.JLabel JLDiente27;
    public javax.swing.JLabel JLDiente28;
    public javax.swing.JLabel JLDiente29;
    public javax.swing.JLabel JLDiente3;
    public javax.swing.JLabel JLDiente30;
    public javax.swing.JLabel JLDiente31;
    public javax.swing.JLabel JLDiente32;
    public javax.swing.JLabel JLDiente4;
    public javax.swing.JLabel JLDiente5;
    public javax.swing.JLabel JLDiente6;
    public javax.swing.JLabel JLDiente7;
    public javax.swing.JLabel JLDiente8;
    public javax.swing.JLabel JLDiente9;
    private javax.swing.JLabel Odontograma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLDienteSel;
    public javax.swing.JLabel jLIDDentista;
    public javax.swing.JLabel jLIDPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTDescipcion;
    // End of variables declaration//GEN-END:variables
}
